### ISSUE TITLE
404，您请求的文件不存在

### ISSUE THREAD

**Issue by yj440** [Archeb/MailValidate#2]
![image](https://user-images.githubusercontent.com/35650528/49658378-e0d8e680-fa7c-11e8-9cc9-26fed56e20aa.png)
点击此链接后，跳转到xxx.cn/MailValidate/send
404，您请求的文件不存在。
![image](https://user-images.githubusercontent.com/35650528/49658455-0d8cfe00-fa7d-11e8-811a-4c38b1f3bde8.png)

**Comment by Archeb** [comment]
是否开启了URL重写？
